name: EzChat
author: FixedDev
main: me.fixeddev.ezchat.ChatPlugin
version: ${project.version}
api-version: 1.13
softdepend:
  - PlaceholderAPI
libraries:
  - "net.kyori:adventure-api:4.13.1"
  - "net.kyori:adventure-text-serializer-gson:4.13.1"
  - "net.kyori:adventure-text-serializer-legacy:4.13.1"